# Generated by Django 5.0.2 on 2024-02-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pointofinterest',
            table='points_of_interest',
        ),
    ]
