# Generated by Django 5.0.2 on 2024-02-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='external_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
